/***************************************************************
** WTW00000006 Captus: 2025 Saint Barnabas Hospital Physician Rates
***************************************************************/
insert into r_rate_variable ( id, name, display_value, value_type ) values ( gen_id(next_r_variable_id,1), 'Provider Specialty - St Barnabas 25', 'Provider Specialty', 'VALUES' );

INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 1' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 2' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 3' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 4' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 5' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 6' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 7' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Oncology' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 8' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Infectious Diseases' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 9' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Interventional Radiology' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Gastroenterology' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Nephrology' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 10' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 11' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 12' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Osteopathic Manipulative Medicine' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Physiatry' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Endocrinology' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 13' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 14' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 15' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 16' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 17' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Certified Nurse Midwife' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Psychiatry including Supervision' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Class 18' );
INSERT INTO R_RATE_VARIABLE_GROUP_VALUE (ID, VARIABLE_ID, GROUP_VALUE ) VALUES ( gen_id(next_r_variable_group_value_id,1), gen_id(next_r_variable_id,0), 'Certified Nurse Practitioner' );

INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 1'), 'Neurosurgery','NEUROSURGERY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 2'), 'Obstetrics - Gynecolgy','OBSTETRICS - GYNECOLGY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 3'), 'General Surgery (Including Bariatric)','GENERAL SURGERY (INCLUDING BARIATRIC)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 4'), 'Orthopedic Surgery','ORTHOPEDIC SURGERY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 5'), 'General Surgery (Excluding Bariatric)','GENERAL SURGERY (EXCLUDING BARIATRIC)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 6'), 'Gynecologic (No Surgery)','GYNECOLOGIC (NO SURGERY)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 6'), 'Otorhinolaryngology Surgery (Including Plastic)','OTORHINOLARYNGOLOGY SURGERY (INCLUDING PLASTIC)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 6'), 'Plastic Surgery','PLASTIC SURGERY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 6'), 'Vascular Surgery','VASCULAR SURGERY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 7'), 'Colon & Rectal Surgery','COLON & RECTAL SURGERY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 7'), 'General Practice w/limited major surgery','GENERAL PRACTICE W/LIMITED MAJOR SURGERY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 7'), 'Neurology incl. supervision','NEUROLOGY INCL. SUPERVISION');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 7'), 'Otorhinolaryngology Surgery (Excluding Plastic)','OTORHINOLARYNGOLOGY SURGERY (EXCLUDING PLASTIC)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 7'), 'Urology incl major surgery','UROLOGY INCL MAJOR SURGERY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Oncology'), 'Oncology','ONCOLOGY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 8'), 'Diagnostic Radiology (No Surgery)','DIAGNOSTIC RADIOLOGY (NO SURGERY)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Infectious Diseases'), 'Infectious Diseases','INFECTIOUS DISEASES');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 9'), 'Emergency Medicine','EMERGENCY MEDICINE');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Interventional Radiology'), 'Interventional Radiology','INTERVENTIONAL RADIOLOGY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Gastroenterology'), 'Gastroenterology (Minor Surgery)','GASTROENTEROLOGY (MINOR SURGERY)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Nephrology'), 'Nephrology','NEPHROLOGY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 10'), 'Internal Medicine (Minor Surgery)','INTERNAL MEDICINE (MINOR SURGERY)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 11'), 'Anesthesiolgy-Pain Management','ANESTHESIOLGY-PAIN MANAGEMENT');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 11'), 'Family Practice (Minor Surgery)','FAMILY PRACTICE (MINOR SURGERY)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 11'), 'Internal Medicine - ICU/Critical Care','INTERNAL MEDICINE - ICU/CRITICAL CARE');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 11'), 'Otorhinolaryngology (No Surgery)','OTORHINOLARYNGOLOGY (NO SURGERY)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 12'), 'Neurology excl. supervision','NEUROLOGY EXCL. SUPERVISION');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Osteopathic Manipulative Medicine'), 'Osteopathic Manipulative Medicine','OSTEOPATHIC MANIPULATIVE MEDICINE');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Physiatry'), 'Physiatry','PHYSIATRY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Endocrinology'), 'Endocrinology','ENDOCRINOLOGY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 13'), 'Anesthesiology','ANESTHESIOLOGY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 14'), 'Dermatology (Minor Surgery)','DERMATOLOGY (MINOR SURGERY)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 14'), 'Internal Medicine (No Surgery)','INTERNAL MEDICINE (NO SURGERY)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 14'), 'Urology','UROLOGY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 15'), 'Ophthalmologic Surgery','OPHTHALMOLOGIC SURGERY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 16'), 'Family Practice (No Surgery)','FAMILY PRACTICE (NO SURGERY)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 16'), 'Neonatology','NEONATOLOGY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 16'), 'Ophthalmologic Surgery (Minor Surgery)','OPHTHALMOLOGIC SURGERY (MINOR SURGERY)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 16'), 'Pediatrics (No Surgery)','PEDIATRICS (NO SURGERY)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 17'), 'Hematology','HEMATOLOGY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 17'), 'Pathology','PATHOLOGY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Certified Nurse Midwife'), 'Certified Nurse Midwife','CERTIFIED NURSE MIDWIFE');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Psychiatry including Supervision'), 'Psychiatry including Supervision','PSYCHIATRY INCLUDING SUPERVISION');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 18'), 'Allergy','ALLERGY');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 18'), 'Dermatology (No Surgery)','DERMATOLOGY (NO SURGERY)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 18'), 'Ophthalmologic Surgery (No Surgery)','OPHTHALMOLOGIC SURGERY (NO SURGERY)');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 18'), 'Physical Medicine & Rehabilitation','PHYSICAL MEDICINE & REHABILITATION');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Class 18'), 'Psychiatry excluding Supervision','PSYCHIATRY EXCLUDING SUPERVISION');
INSERT INTO R_RATE_VARIABLE_ITEM_VALUE (VARIABLE_GROUP_ID, ITEM_VALUE, UPPER_ITEM_VALUE) VALUES ((select id from r_rate_variable_group_value rvgv where rvgv.variable_id = gen_id(next_r_variable_id,0) and rvgv.group_value = 'Certified Nurse Practitioner'), 'Certified Nurse Practitioner','CERTIFIED NURSE PRACTITIONER');

commit;

/* St Barnabas Rates */
INSERT INTO MASTER_POLICY(MASTER_POLICY_SEQNO, RRG_ID, POLICY_NUMBER, PREVIOUS_POLICY_NUMBER, POLICY_EFFECTIVE, POLICY_CANCELLATION, DEDUCTIBLE, ESTIMATED_PREMIUM, TRUE_UP_PREMIUM, HPL_OCCURRENCE_LIMIT, HPL_AGGREGATE_LIMIT, PPL_OCCURRENCE_LIMIT, PPL_AGGREGATE_LIMIT, GL_OCCURRENCE_LIMIT, GL_AGGREGATE_LIMIT, REL_ACUTE_CARE, REL_NURSERY,  REL_PSYCHIATRICS, REL_REHAB, REL_SKILLED_NURSING, REL_INDEPENDENT_LIVING, REL_ASSISTED_LIVING, REL_EXTENDED_CARE, REL_SKILLED_CARE, REL_RESIDENTIAL_CARE, REL_DELIVERIES, REL_INPATIENT_SURGERIES, REL_ER, REL_HOMEHEALTHCARE_PROF,  REL_HOMEHEALTHCARE_NONPROF, REL_SURGICAL, REL_CLINICS, REL_URGENT_CARE, REL_OTHER, REL_HOSPITAL, REL_WAREHOUSE, REL_PARKING, LAST_UPDATED_BY ) VALUES (gen_id(next_master_policy_seqno, 1), 1007,   '2025STBARNABAS', '2024STBARNABAS', '1/1/2025', '1/1/2026',0,0,0,0,0,1000000,3000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'SYSDBA' );		
--MPC	--Assmt.	--Req Var
INSERT INTO MASTER_POLICY_COVERAGE (MASTER_POLICY_COVERAGE_SEQNO,  MASTER_POLICY_SEQNO, INSURANCE_TYPE_ID,  LAST_UPDATED_BY ) VALUES (gen_id(next_master_policy_cov_seqno,1), gen_id(next_master_policy_seqno,0), 'PhysiciansLiability', 'SYSDBA' );	INSERT INTO R_ASSESSMENT (ID, ASSESSMENT_TYPE, NAME, DISPLAY_NAME, ORDER_ALGORITHM, ROUNDING_LEVEL, VALID_ASSESSMENT, DATE_APPLIED, META_SURCHARGE, TRANSACTION_CODE, LAST_UPDATED_BY) VALUES (gen_id(next_r_assessment_id, 1), 'PREMIUM', 'St Barnabas Physicians 2025', 'St Barnabas Physicians 2025', 'PHYSICIAN', 'DOLLAR', 'True', 'EFFECTIVE', 'False', NULL, 'SYSDBA');	INSERT INTO R_ASSESSMENT_REQ_VAR (ID, ASSESSMENT_ID, VARIABLE_ID) VALUES (gen_id(next_r_assessment_req_var_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'));
		
--Page	--Link	--Cust No
INSERT INTO R_RATE_PAGE (ID, VALID_PAGE, LAST_UPDATED_BY) VALUES (gen_id(next_r_page_id,1), 'True', 'SYSDBA');	INSERT INTO R_RATE_PAGE_ASSESSMENT_LINK (ID, RATE_PAGE_ID, ASSESSMENT_ID) VALUES (gen_id(next_r_page_assessment_link_id,1),gen_id(next_r_page_id,0),(select id from r_assessment where name = 'St Barnabas Physicians 2025'));	INSERT INTO HOSPITAL_MPC_LINK (HOSPITAL_NUMBER, HOSPITAL_ID, MASTER_POLICY_COVERAGE_SEQNO, HOSPITAL_EFFECTIVE, HOSPITAL_EXPIRATION, RATE_PAGE_ID, BILLING_MIN_MONTHS, BILLING_ROUNDING_FACTOR, LAST_UPDATED_BY,    WILDCARD_COUNT) VALUES ('V25A', 40000141, (select mpc.master_policy_coverage_seqno from master_policy_coverage mpc join master_policy mp on mp.master_policy_seqno = mpc.master_policy_seqno where mp.master_policy_seqno = (gen_id(next_master_policy_seqno,0)) and mpc.insurance_type_id = 'PhysiciansLiability'),'1/1/2025', '1/1/2026', gen_id(next_r_page_id,0),NULL, NULL,'SYSDBA', 0 );
		
		
		
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 138331.7228,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 1'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 84324.37161,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 2'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 75788.2967,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 3'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 62819.11271,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 4'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 50526.38202,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 5'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 48931.82416,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 6'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 27639.28642,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 7'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 25374.23146,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 8'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 25374.23146,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Oncology'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 24490.16229,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 9'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 23824.77049,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Infectious Diseases'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 20470.58316,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 10'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 20299.15239,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Interventional Radiology'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 19496.32022,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 11'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 19496.32022,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Gastroenterology'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 19496.32022,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Nephrology'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 18814.76161,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 12'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 16522.03224,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Osteopathic Manipulative Medicine'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 16522.03224,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Physiatry'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 16192.33509,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 13'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 15814.5423,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 14'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 15814.5423,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Endocrinology'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 15668.19014,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 15'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 11531.18892,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 16'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 11210.4054,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 17'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 9189.554332,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Certified Nurse Midwife'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 5817.923865,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Psychiatry including Supervision'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 4654.339092,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Class 18'));
INSERT INTO R_RATE (ID, ASSESSMENT_ID, RATE_CONSTANT, RATE_PERCENT, CANCEL_ALGORITHM, VALID_RATE, WILDCARD_COUNT, LAST_UPDATED_BY) VALUES (gen_id(next_r_rate_id,1), (select id from r_assessment where name = 'St Barnabas Physicians 2025'), 1837.910866,   0, 'PRO_RATA', 'True', 0, 'SYSDBA');	INSERT INTO R_RATE_PREMIUM (ID, OCCURRENCE_LIMIT, AGGREGATE_LIMIT) VALUES (gen_id(next_r_rate_id,0), 1000000,3000000);	INSERT INTO R_RATE_VARIABLE_VALUE_MAP (ID, RATE_ID, VARIABLE_ID, VARIABLE_VALUE_ID) VALUES (gen_id(next_r_variable_value_map_id,1), gen_id(next_r_rate_id,0), (select id from r_rate_variable where name = 'Provider Specialty - St Barnabas 25'), (select vgv.id from r_rate_variable_group_value vgv join r_rate_variable v on vgv.variable_id = v.id where v.name = 'Provider Specialty - St Barnabas 25' and vgv.group_value = 'Certified Nurse Practitioner'));

commit;

/*********************************************************
 St Barnabas doesn't have any taxes
*********************************************************/
